#!/bin/sh
# 서브모듈 업데이트
git submodule update --remote

# git diff 결과 중 "Subproject" 문자열이 있으면, push 중단
if git diff --exit-code | grep -q 'Subproject'; then
    echo "서브모듈 변경 사항이 감지되었습니다. 커밋 후 다시 push 해주세요."
    exit 1
fi
