networks:
  app-tier:
    driver: bridge
services:
  techlog-blue:
    container_name: techlog-blue
    networks:
      - app-tier
    depends_on:
      - mysql
    image: techlogv1/techlog_dev:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    healthcheck:
      test: "curl -f http://localhost:8080/check/health || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./logs:/app/logs

  techlog-green:
    container_name: techlog-green
    networks:
      - app-tier
    depends_on:
      - mysql
    image: techlogv1/techlog_dev:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: always
    healthcheck:
      test: "curl -f http://localhost:8080/check/health || exit 1"
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - ./logs:/app/logs

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - ./mysql.env
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-tier

  nginx:
    depends_on:
      - techlog-green
      - techlog-blue
    image: nginx:1.15-alpine
    container_name: nginx
    networks:
      - app-tier
    restart: unless-stopped
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/log:/var/log/nginx
      - /etc/localtime:/etc/localtime
    ports:
      - "80:80"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./logs:/var/log/techlog
      - ./promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /tmp:/tmp
    command: -config.file=/etc/promtail/config.yaml -log.level=debug
    restart: unless-stopped
    networks:
      - app-tier
