spring:
  config:
    import: env-common.yml

  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 100

  jackson:
    time-zone: UTC
