name: DEV CD

on:
  workflow_dispatch:
  pull_request:
    branches: [ dev ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN }}
      - name: Debug - List submodule folder contents
        run: |
          ls -Rla ./techlog-env

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/techlog_dev:latest .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/techlog_dev:latest

      - name: Copy deployment files
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEV_HOST_IP }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_HOST_KEY }}
          port: 22
          timeout: 120s
          source: "deployment/dev/,techlog-env/back/mysql.env"
          target: /home/techlog
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_HOST_IP }}
          username: ${{ secrets.DEV_USERNAME }}
          key: ${{ secrets.DEV_HOST_KEY }}
          port: 22
          script: |
            rm -rf ~/data
            mv ~/deployment/dev/* ~/
            mv ~/techlog-env/back/mysql.env ~/
            rm -rf ~/deployment
            rm -rf ~/techlog-env
            bash ./deploy.sh
